"""empty message

Revision ID: 35ec8c45a945
Revises: 3765ccc5f2a2
Create Date: 2022-03-14 01:02:27.482907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ec8c45a945'
down_revision = '3765ccc5f2a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_fname', sa.String(length=50), nullable=False),
    sa.Column('user_lname', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_password', sa.String(length=500), nullable=False),
    sa.Column('user_address', sa.String(length=100), nullable=False),
    sa.Column('user_phone', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.add_column('cards', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'cards', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='unique')
    op.drop_column('cards', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
