"""empty message

Revision ID: 3765ccc5f2a2
Revises: 
Create Date: 2022-03-13 19:00:17.233263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3765ccc5f2a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cardnumber', sa.String(length=16), nullable=False),
    sa.Column('cardexpirydate', sa.String(length=5), nullable=False),
    sa.Column('cardcvvnum', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
