"""empty message

Revision ID: 72b5424128d4
Revises: 
Create Date: 2022-03-17 00:31:16.250431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b5424128d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallet_num', sa.String(length=50), nullable=True),
    sa.Column('third_party_account', sa.String(length=50), nullable=True),
    sa.Column('account_status', sa.String(length=20), nullable=True),
    sa.Column('ngn_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('usd_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('third_party_account'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('wallet_num')
    )
    op.create_table('bank_funding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallet_num', sa.String(length=50), nullable=True),
    sa.Column('third_party_num', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('get_wallet_code', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cardnumber', sa.String(length=16), nullable=False),
    sa.Column('cardexpirydate', sa.String(length=5), nullable=False),
    sa.Column('cardcvvnum', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallet_num', sa.String(length=50), nullable=True),
    sa.Column('posting_type', sa.String(length=5), nullable=True),
    sa.Column('reference', sa.String(length=1000), nullable=True),
    sa.Column('third_party_reference', sa.String(length=1000), nullable=True),
    sa.Column('transaction_type', sa.String(length=100), nullable=True),
    sa.Column('transaction_service', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('transaction_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_before_transaction', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_after_transaction', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('provider_details', sa.String(length=1000), nullable=True),
    sa.Column('to_wallet_id', sa.String(length=1000), nullable=True),
    sa.Column('customer_ref', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_fname', sa.String(length=50), nullable=False),
    sa.Column('user_lname', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_password', sa.String(length=500), nullable=False),
    sa.Column('user_address', sa.String(length=100), nullable=False),
    sa.Column('user_phone', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('transactions')
    op.drop_table('cards')
    op.drop_table('banks')
    op.drop_table('bank_funding')
    op.drop_table('accounts')
    # ### end Alembic commands ###
