"""empty message

Revision ID: 8fc91eff8b77
Revises: 35ec8c45a945
Create Date: 2022-03-14 22:00:08.753362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc91eff8b77'
down_revision = '35ec8c45a945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallet_num', sa.String(length=50), nullable=True),
    sa.Column('third_party_account', sa.String(length=50), nullable=True),
    sa.Column('account_status', sa.String(length=20), nullable=True),
    sa.Column('ngn_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('usd_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('third_party_account'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('wallet_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
