"""empty message

Revision ID: a4f4ba364a75
Revises: 5fcc55dcdf9b
Create Date: 2022-03-20 02:51:00.547845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f4ba364a75'
down_revision = '5fcc55dcdf9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_funding', sa.Column('account_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_funding', 'account_name')
    # ### end Alembic commands ###
