"""empty message

Revision ID: eb7ac18f5d84
Revises: 2a4484ca0601
Create Date: 2022-03-17 00:43:33.282927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb7ac18f5d84'
down_revision = '2a4484ca0601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'cardnumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('cardnumber', mysql.VARCHAR(length=16), nullable=False))
    # ### end Alembic commands ###
