"""empty message

Revision ID: f8616dc0780b
Revises: eb7ac18f5d84
Create Date: 2022-03-17 00:44:01.558284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8616dc0780b'
down_revision = 'eb7ac18f5d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('cardnumber', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'cardnumber')
    # ### end Alembic commands ###
